name: Deploy

on:
  push:
    branches:
      - development

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-node@v1
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_DAN}}
          heroku_app_name: "gps-project-group1" #Must be unique in Heroku
          heroku_email: "daniel.rodrigues.cavadas@gmail.com"
          appdir: "./frontend" # <- This will point to the api folder in your project
  build-backend:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1

      - name: Add remote origin
        working-directory: ./backend
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY_DAN }}@git.heroku.com/gps-project-group1-backend.git

      - name: Deploy backend to heroku
        working-directory: ./backend
        run: git push --force heroku `git subtree split --prefix backend HEAD`:master
    #steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v1
      #- name: Setup frontend
        #working-directory: ./frontend
        #run: |
          #npm install
          #npm run build
      #- uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        #with:
          #heroku_api_key: ${{secrets.HEROKU_API_KEY_DAN}}
          #heroku_app_name: "gps-project-group1-backend" #Must be unique in Heroku
          #heroku_email: "daniel.rodrigues.cavadas@gmail.com"
          #appdir: "./backend" # <- This will point to the api folder in your project
          #procfile: "web: node index.js"
